// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx4vzL2ZYP-XGRNqp0sxxPw8Aljo1FHOo',
    appId: '1:3007047369:web:17b8dbc876212149bdcf18',
    messagingSenderId: '3007047369',
    projectId: 'chat-apps-453d2',
    authDomain: 'chat-apps-453d2.firebaseapp.com',
    storageBucket: 'chat-apps-453d2.appspot.com',
    measurementId: 'G-KS4E2DH6W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCajbKKFeN-U4K40-tX-31u3kV78waalgg',
    appId: '1:3007047369:android:b5f96a92c97c0101bdcf18',
    messagingSenderId: '3007047369',
    projectId: 'chat-apps-453d2',
    storageBucket: 'chat-apps-453d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-AedtHYTwSPgBaQ6ZAxA0wHC8HQfk524',
    appId: '1:3007047369:ios:f80c90e2d3ec74e8bdcf18',
    messagingSenderId: '3007047369',
    projectId: 'chat-apps-453d2',
    storageBucket: 'chat-apps-453d2.appspot.com',
    iosClientId: '3007047369-mfk312uinfij2ri1ef6arvifs1q5r2hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-AedtHYTwSPgBaQ6ZAxA0wHC8HQfk524',
    appId: '1:3007047369:ios:f80c90e2d3ec74e8bdcf18',
    messagingSenderId: '3007047369',
    projectId: 'chat-apps-453d2',
    storageBucket: 'chat-apps-453d2.appspot.com',
    iosClientId: '3007047369-mfk312uinfij2ri1ef6arvifs1q5r2hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppTwo',
  );
}
